spring:
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db;MODE=MYSQL
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    database: h2
  sql:
    init:
      data-locations: classpath:import.sql
